db:
  image: mongo
  ports:
    - "27017:27017"
  restart: always
web:
  build: .
  volumes:
     - ./:/app
     - /usr/local/lib/node_modules
  ports:
     - "5000:5000"
  links:
     - db
  command: node /app/index.js
